CREATE DATABASE  IF NOT EXISTS `horseracing` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `horseracing`;

CREATE TABLE IF NOT EXISTS `race` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `fixresult` BOOL NULL,
  PRIMARY KEY (`id`))
ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `horse` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `runner` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `race_id` INTEGER NOT NULL,
  `horse_id` INTEGER NOT NULL,
  `rate` DECIMAL(15,2) NULL,
  `place` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_runner_race`
    FOREIGN KEY (`race_id`)
    REFERENCES `race` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
    FOREIGN KEY (`horse_id`)
    REFERENCES `horse` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `balance` DECIMAL(15,2) NULL,
  `role` INTEGER NOT NULL,
  PRIMARY KEY (`id`))
ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `bet` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `user_id` INTEGER NOT NULL,
  `runner_id` INTEGER NOT NULL,
  `bettype` INTEGER NOT NULL,
  `bettime` TIMESTAMP NOT NULL,
  `finalrate` DECIMAL(15,2) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `win` BOOL NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_bet_runners`
    FOREIGN KEY (`runner_id`)
    REFERENCES `runner` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_bet_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE=INNODB DEFAULT CHARACTER SET utf8;
